spring.application.name=Flatmate
spring.datasource.url=jdbc:postgresql://localhost:5432/flatmate_db
spring.datasource.username=YourDatabaseUsername
spring.datasource.password=YourDatabasePassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8081

jwt.secret=Your_JWT_Secret_Key_Minimum_32_Characters
jwt.expiration=86400000


groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=Your_Groq_API_Key
groq.model=llama-3.3-70b-versatile

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YourEmail
spring.mail.password=Gmail_APP_Password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO